# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='picture',
            field=models.ImageField(default='circus.png', upload_to='officer_pics/'),
        ),
    ]
