# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0002_officer_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='major',
            field=models.TextField(default='Undeclared'),
        ),
        migrations.AddField(
            model_name='officer',
            name='position',
            field=models.TextField(default='Intern'),
        ),
    ]
