# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0003_auto_20160326_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='major',
            field=models.CharField(default='Undeclared', max_length=30),
        ),
        migrations.AlterField(
            model_name='officer',
            name='position',
            field=models.CharField(default='Intern', max_length=30),
        ),
    ]
