# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 00:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0004_auto_20160326_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('event_date', models.DateField(default=datetime.date.today)),
                ('facebook_link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='officer',
            name='ordering',
            field=models.IntegerField(default=10),
        ),
    ]
